Repository kokonior/Python-Projects, pull requests merged in 2021-10, with the labels that each got.

#2 Create day-to-hour.md
  snippets/day-to-hour.md
Labels: hacktoberfest-accepted, Create

#1 Create Luas-Segitiga
  Luas-Segitiga
Labels: hacktoberfest-accepted, Create

#3 Create Calculator With Python
  Calculator
Labels: hacktoberfest-accepted, Create

#5 Find the radius of a circle in Indonesia
  Radius-Circle (IND)
Labels: good first issue, hacktoberfest-accepted

#4 Create reverse string.md
  snippets/reverse string.md
Labels: hacktoberfest-accepted, Create

#9 Create efanwahyu.py
  efanwahyu.py
Labels: hacktoberfest-accepted, Create

#13 Create riodelord.py
  riodelord.py
Labels: hacktoberfest-accepted, Create

#12 Create Palindrom.py
  Palindrom.py
Labels: hacktoberfest-accepted, Create

#11 Create random_dice.py
  random_dice.py
Labels: hacktoberfest-accepted, Create

#8 Added isprime program
  snippets/isprime.md
Labels: hacktoberfest-accepted

#7 add .py file extension
  Calculator.py
  Luas-Segitiga.py
  Radius-Circle (IND).py
Labels: enhancement, hacktoberfest-accepted

#6 Calculate the circumference of a circle
  Circuference Circle
Labels: good first issue, hacktoberfest-accepted

#16 Create avl-trees.py
  avl-trees.py
Labels: hacktoberfest-accepted, Create

#15 Create bimaexz.py
  bimaexz.py
Labels: hacktoberfest-accepted, Create

#17 moved code into a code folder
  code/Calculator.py
  code/Circuference Circle.py
  code/Luas-Segitiga.py
  code/Palindrom.py
  code/Radius-Circle (IND).py
  code/efanwahyu.py
  code/random_dice.py
  code/riodelord.py
Labels: enhancement, hacktoberfest-accepted

#18 Create run_avl_trees.py
  run_avl_trees.py
Labels: hacktoberfest-accepted, Create

#19 Create Employee.py
  code/Employee.py
Labels: hacktoberfest-accepted, Create

#22 Create inherit.py
  code/inherit.py
Labels: hacktoberfest-accepted, Create

#21 Update avl-trees.py
  avl-trees.py
Labels: hacktoberfest-accepted

#20 Masker Detection
  code/Masker Detection - Haar Cascade.py
Labels: good first issue, hacktoberfest-accepted

#23 Update README.md
  README.md
Labels: hacktoberfest-accepted

#24 added a Turtle Race game which I made using Python and Turtle
  code/turtle_race.py
Labels: hacktoberfest-accepted

#25 moved code
  code/avl-trees.py
  code/bimaexz.py
  code/run_avl_trees.py
Labels: good first issue, hacktoberfest-accepted

#26 Add files via upload
  code/Bot katanya.py
Labels: enhancement, hacktoberfest-accepted

#29 Create hello.py
  code/hello.py
Labels: hacktoberfest-accepted, Create

#28 Create Calculate Area and Perimeter of a Rectangle
  code/Python Program to Calculate Area and Perimeter of a Rectangle
Labels: hacktoberfest-accepted, Create

#27 Create fibonacci.py
  code/fibonacci.py
Labels: hacktoberfest-accepted, Create

#30 Update hello.py
  code/hello.py
Labels: enhancement, hacktoberfest-accepted

#32 Create russss.py
  code/russss.py
Labels: hacktoberfest-accepted, Create

#33 Add files via upload
  code/factorial.py
  code/factors.py
  code/prime.py
  code/pyramid1.py
  code/pyramid2.py
  code/replacevowel.py
  code/reverse.py
  code/string.py
  code/vowel.py
  code/wordcount.py
Labels: hacktoberfest-accepted

#34 Create Python_String_Formatting.py
  Python_String_Formatting.py
Labels: hacktoberfest-accepted, Create

#35 adding a guessing game
  code/Guessing game (Ujjawal179)
Labels: enhancement, hacktoberfest-accepted

#36 mahasiswa.py: ambil info mahasiswa dari Kemdikbud
  code/mahasiswa.py
Labels: enhancement, hacktoberfest-accepted

#37 Generate random x digit number
  code/rand_x_number.py
Labels: enhancement, hacktoberfest-accepted

#38 Youtube Video Downloader
  code/Youtube Video Downloader/Youtube_Vid_Downloader.py
  code/Youtube Video Downloader/readme.md
Labels: hacktoberfest-accepted

#39 Added Technofrost userlogin system
  code/Python User Login system(TechnoFrost27).py
Labels: enhancement, hacktoberfest-accepted

#40 Create reddit.py
  code/reddit.py
Labels: hacktoberfest-accepted, Create

#46 Create FirmanKurniawan.py label:hacktoberfest-accepted
  FirmanKurniawan.py
Labels: hacktoberfest-accepted, Create

#45 Create arzyware.py
  code/arzyware.py
Labels: hacktoberfest-accepted, Create

#48 Create hendrastwn.py
  hendrastwn.py
Labels: hacktoberfest-accepted

#47 Update arzyware.py
  code/arzyware.py
Labels: enhancement, hacktoberfest-accepted

#50 Update hendrastwn.py
  hendrastwn.py
Labels: enhancement, hacktoberfest-accepted

#51 Add files via upload
  elbasrie.py
Labels: enhancement, hacktoberfest-accepted

#49 Create Matrix.py
  code/Matrix.py
Labels: hacktoberfest-accepted

#52 Create konveksi-suhu.py
  konveksi-suhu.py
Labels: hacktoberfest-accepted, Create

#53 Add ahorcado game py file and a Lexicon.txt file
  code/ahorcadoGame/Ahorcado Game.py
  code/ahorcadoGame/Lexicon.txt
Labels: hacktoberfest-accepted

#54 IP Generator
  ipgen.py
Labels: hacktoberfest-accepted

#57 Create parsejson.md
  snippets/parsejson.md
Labels: hacktoberfest-accepted, Create

#56 Update arzyware.py
  code/arzyware.py
Labels: enhancement, hacktoberfest-accepted

#55 simplekalkulator.py
  code/kalkulator.py
Labels: hacktoberfest-accepted

#58 Scissor rock paper game
  scissor_rock_paper.py
Labels: hacktoberfest-accepted

#60 Update arzyware.py
  code/arzyware.py
Labels: hacktoberfest-accepted

#59 Program to calculating the area of plane figure
  area_plane_figure.py
  program_nilai_akhir.py
Labels: hacktoberfest-accepted

#63 alakadutz
  alakadutz
Labels: hacktoberfest-accepted

#61 Tkinter app Parkir
  tkinter_parkir_simple.py
Labels: hacktoberfest-accepted

#64 Create no urut.py
  no urut.py
Labels: hacktoberfest-accepted, Create

#65 Create recursive-function.py
  recursive-function.py
Labels: hacktoberfest-accepted, Create

#201 Create keyLogger.py
  keyLogger.py
Labels: hacktoberfest-accepted

#200 Create Translator.py
  Translator.py
Labels: hacktoberfest-accepted

#199 Password_Generator_Using_Python
  PasswordGenerator_pawarspeaks.py
Labels: hacktoberfest-accepted

#198 Stop Watch_
  Stop Watch_
Labels: hacktoberfest-accepted

#214 Update
  main.py
Labels: hacktoberfest-accepted

#213 Linear Regression using Least Square method in python
  Linear Regression.ipynb
Labels: hacktoberfest-accepted

#212 Add example of method overloading in python
  method_overloading_in_python.py
Labels: hacktoberfest-accepted

#210 contact management in python
  manajemen kontak sederhana/__pycache__/function.cpython-37.pyc
  manajemen kontak sederhana/__pycache__/function.cpython-38.pyc
  manajemen kontak sederhana/app.py
  manajemen kontak sederhana/function.py
  manajemen kontak sederhana/readme.md
Labels: hacktoberfest-accepted

#209 Create HourGlass_Matrix_Question_,print_max_sum.py
  HourGlass_Matrix_Question_,print_max_sum.py
Labels: hacktoberfest-accepted

#208 Create Insert_elements_in_BST.py
  Insert_elements_in_BST.py
Labels: hacktoberfest-accepted

#207 Create Largest_Sum_Continuous_Subarray.py
  Largest_Sum_Continuous_Subarray.py
Labels: hacktoberfest-accepted

#206 Create Pattern_Matching_using_naive_algo.py
  Pattern_Matching_using_naive_algo.py
Labels: hacktoberfest-accepted

#205 Create Anagrams.py
  Anagrams.py
Labels: hacktoberfest-accepted

#204 Create Next_Permutation_of_an_array.py
  Next_Permutation_of_an_array.py
Labels: hacktoberfest-accepted

#203 Create Prefix_sum.py
  Prefix_sum.py
Labels: hacktoberfest-accepted

#202 Create Josephus_algo.py
  Josephus_algo.py
Labels: hacktoberfest-accepted
